# References:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- powershell: |
    $url = "github.com/BeardedPlatypus/rubber-squid.git"
    $url = ":$env:GITHUB_PW@$url"
    $url = "$env:GITHUB_ACCOUNT$url"
    $url = "https://$url"

    git clone $url "theme/rubber-squid"
  displayName: 'Check out - Rubber Squid Theme'
  env:
    GITHUB_ACCOUNT: $(github.profile)
    GITHUB_PW: $(github.password)

- powershell: |
    $url = "github.com/BeardedPlatypus/personal-website-content.git"
    $url = ":$env:GITHUB_PW@$url"
    $url = "$env:GITHUB_ACCOUNT$url"
    $url = "https://$url"

    git clone $url content
  displayName: 'Check out - Blog Content'
  env:
    GITHUB_ACCOUNT: $(github.profile)
    GITHUB_PW: $(github.password)

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install python dependencies'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    gulp prePelican
  displayName: 'Pre-Pelican Compile'

- script: |
    pelican content -s publishconf.py
  displayName: 'Pelican Compile'

- script: |
    gulp postPelican
  displayName: 'Post-Pelican Compile'
